const express = require('express')
const mongoose = require('mongoose')
const cors = require('cors')
require('dotenv').config()
const app = express()
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173', credentials: true }))
app.use(express.json())
app.use('/api/auth', require('./routes/auth'))
app.use('/api/projects', require('./routes/projects'))
app.use('/api/tasks', require('./routes/tasks'))
mongoose.connect(process.env.MONGO_URI).then(() => {
    console.log('mongodb connected')
    app.listen(process.env.PORT, () => console.log(`running on port ${process.env.PORT}`))
}).catch(err => console.error(err))